In [1]:
import numpy as np
#create matrices
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#Addition
C = A+B

#subtraction
D = A-B

#Multipication ((elementwise)
E = A*B

#matrix multiplication
F = np.dot(A, B) #or A @ B

#transpose
A_transpose=A.T
B_transpose=B.T



print("Addition:")
print(C)

print("Subtraction:")
print(D)

print("Element-wise multiplication:")
print(E)

print("Matrix multiplication")
print(F)

print("\n Transpose")
print(A_transpose)
print(B_transpose)


Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]
Element-wise multiplication:
[[ 5 12]
 [21 32]]
Matrix multiplication
[[19 22]
 [43 50]]

 Transpose
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]
